name: create release from tag

on: 
  push:
    tags:
    - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup-node
      uses: actions/setup-node@v2
      with:
        node-version: '17'
    - name: build
      run: npm install && npm run build
    - name: zip
      run:
        |
        TAG_NAME="${GITHUB_REF/refs\/tags\//}"
        cd build
        zip "../systemet-${TAG_NAME}.zip" ./*
    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "systemet-*.zip"
        generateReleaseNotes: true
